-- MySQL Script generated by MySQL Workbench
-- Thu Apr 13 13:50:00 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema abhishekb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema abhishekb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `abhishekb` DEFAULT CHARACTER SET latin1 ;
USE `abhishekb` ;

-- -----------------------------------------------------
-- Table `abhishekb`.`Author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abhishekb`.`Author` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `abhishekb`.`Publisher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abhishekb`.`Publisher` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `contact_name` VARCHAR(255) NULL DEFAULT NULL,
  `contact_email` VARCHAR(255) NULL DEFAULT NULL,
  `location` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `abhishekb`.`Venue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abhishekb`.`Venue` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `organization` VARCHAR(255) NULL DEFAULT NULL,
  `area_of_research` VARCHAR(255) NULL DEFAULT NULL,
  `editor` VARCHAR(255) NULL DEFAULT NULL,
  `editor_contact` VARCHAR(255) NULL DEFAULT NULL,
  `location` VARCHAR(255) NULL DEFAULT NULL,
  `conference_year` INT(10) UNSIGNED NULL DEFAULT NULL,
  `publisher_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_venue_publisher` (`publisher_id` ASC) VISIBLE,
  CONSTRAINT `fk_venue_publisher`
    FOREIGN KEY (`publisher_id`)
    REFERENCES `abhishekb`.`Publisher` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `abhishekb`.`Publication`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abhishekb`.`Publication` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `page_range` VARCHAR(20) NULL DEFAULT NULL,
  `volume` VARCHAR(20) NULL DEFAULT NULL,
  `issue` VARCHAR(20) NULL DEFAULT NULL,
  `month` VARCHAR(20) NULL DEFAULT NULL,
  `year` INT(10) UNSIGNED NULL DEFAULT NULL,
  `venue_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_publication_venue` (`venue_id` ASC) VISIBLE,
  CONSTRAINT `fk_publication_venue`
    FOREIGN KEY (`venue_id`)
    REFERENCES `abhishekb`.`Venue` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `abhishekb`.`Publication_Author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abhishekb`.`Publication_Author` (
  `publication_id` INT(10) UNSIGNED NOT NULL,
  `author_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`publication_id`, `author_id`),
  INDEX `fk_pub_author_author` (`author_id` ASC) VISIBLE,
  CONSTRAINT `fk_pub_author_author`
    FOREIGN KEY (`author_id`)
    REFERENCES `abhishekb`.`Author` (`id`),
  CONSTRAINT `fk_pub_author_pub`
    FOREIGN KEY (`publication_id`)
    REFERENCES `abhishekb`.`Publication` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `abhishekb`.`Research_Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abhishekb`.`Research_Area` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `parent_area_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_area_parent_area` (`parent_area_id` ASC) VISIBLE,
  CONSTRAINT `fk_area_parent_area`
    FOREIGN KEY (`parent_area_id`)
    REFERENCES `abhishekb`.`Research_Area` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `abhishekb`.`Publication_Research_Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abhishekb`.`Publication_Research_Area` (
  `publication_id` INT(10) UNSIGNED NOT NULL,
  `research_area_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`publication_id`, `research_area_id`),
  INDEX `fk_pub_area_area` (`research_area_id` ASC) VISIBLE,
  CONSTRAINT `fk_pub_area_area`
    FOREIGN KEY (`research_area_id`)
    REFERENCES `abhishekb`.`Research_Area` (`id`),
  CONSTRAINT `fk_pub_area_pub`
    FOREIGN KEY (`publication_id`)
    REFERENCES `abhishekb`.`Publication` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `abhishekb`.`Reference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abhishekb`.`Reference` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `citation_string` VARCHAR(255) NOT NULL,
  `publication_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reference_pub` (`publication_id` ASC) VISIBLE,
  CONSTRAINT `fk_reference_pub`
    FOREIGN KEY (`publication_id`)
    REFERENCES `abhishekb`.`Publication` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
